name: Job Dependency Flow

on:
  push:
    branches:
      - main

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Job 1
        run: python job1.py

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Job 2
        run: python job2.py

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Job 3
        run: python job3.py

  job4:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Job 4
        run: python job4.py

  job5:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Job 5
        run: python job5.py

  job6:
    runs-on: ubuntu-latest
    needs: [job4, job5]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Job 6
        run: python job6.py